### ISSUE TITLE
Adventuring Fellow Bond - 'Let's chat'

### ISSUE THREAD

**Issue by panfunk** [EdenServer/community#1810]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

https://github.com/EdenServer/community/issues/1799#issue-458093184

Since above bug report was closed too early imo, I repost this one.
It appears that the 'Let's chat' option at rendevouz points doesnt award any Bond atm.
As Fariska I was able to change my fellows job after calling it 5 times with signal pearl, but since I 'chatted' with my fellow every earth day since Tuesday, this option should have been available much sooner.

Quote from era wiki:
https://ffxiclopedia.fandom.com/wiki/Adventuring_Fellow?oldid=325001

" Calling your Adventuring Fellow at a Rendezvous Point and selecting the option "Let's chat." increases your Adventuring Fellow Bond by 1 (once per real life day). "

" If your bond decreases to less than 5 (by throwing away your Signal Pearl) you will not have the option to change combat styles untill Bond reaches 5 again. "

**Comment by greyenvy** [comment]
Can confirm bond is not granted when using the Let's Chat option.  I had to summon fellow five times with pearl before I could change combat style.

**Comment by bkesecker** [comment]
Fixed by PR: https://github.com/godmode/dsp/pull/869

**Comment by bkesecker** [comment]
Will be in next release.

**Comment by Leonira** [comment]
Has this been implemented since the "next release" comment?
Because this still seems to be the case...

**Comment by InoUno** [comment]
I can confirm that it is still the case that the "Let's chat" does not increase bond as it's supposed to. I just started my fellow, and chatted with it for 3 days now, and had them out 3 times with Signal Pearl, and still can't change their combat style. 
Should this issue be reopened?

**Comment by KnowOne134** [comment]
Just gonna answer the question that I've been advised against doing. You can only get 1 point per day. Either by calling or talking. But not both. 5 days of just talking and never calling is same as 5 days of calling

**Comment by InoUno** [comment]
Thanks for the answer!
Is it intended to be like that though? I'm pretty confident (from memory and from reading the wikis) that you could gain more than 1 bond point/day by both chatting and summoning the fellow. It was only the chatting that was limited to 1 point/day, since otherwise it could just be spammed. There shouldn't be a limit on bond gained from summoning, it should always be +1 point, since that is automatically limited by the cooldown of the Signal Pearl.

**Comment by KnowOne134** [comment]
We believed it was changed to that style after a certain time. In the beginning bond was harder to get and lack of data. Atm retail you can get unlimited bond talking. So it's been changed a few times over the years. And alot of it is a complete mystery in the begining

**Comment by InoUno** [comment]
Did some digging and this is what I've found.

[FFXI update list](https://www.bg-wiki.com/bg/Category:Update_History).
Fellows were added in the [July 19th, 2005 update](http://www.playonline.com/pcd/update/ff11us/20050715Pm01B1/detail.html).

At [November 28th, 2005](https://ffxiclopedia.fandom.com/wiki/Adventuring_Fellow?oldid=26383), the wiki page has the following information (only one FFXI update has occurred in that timeframe): 


> * Each time you use your Signal Pearl or Tactics Pearl you increase your Adventuring Fellow Bond.
> * Calling your Adventuring Fellow at a Rendezvous Point increases your Adventuring Fellow Bond.
> * You can also increase your Adventuring Fellow Bond by completing the following quests:
>   1. Past Reflections (given ~4 summons after the 2nd weapon upgrade)
>   2. Blighted Gloom (given ~3 summons after the 3rd weapon upgrade)

~4 summons after 2nd weapon upgrade pretty much matches the 10 needed bond points from the 2nd weapon upgrade (20 -> 30 points), but only if you account for points gotten for both chatting AND summoning each day for 4-5 days (2 times 4 = ~10 points, depending on when they noticed the weapon upgrade).

~3 summons after the 3rd weapon upgrade also matches the 5 needed bond points (40 -> 45), if you account for points from both chatting AND summoning for 3 days (2 times 3 = ~5 points).


Then at [January 11, 2006](https://ffxiclopedia.fandom.com/wiki/Adventuring_Fellow?oldid=30237), the wiki explicitly mentions that each of the actions give 1 point, with no mention of any limits, even though there probably was one on chatting already (this note was added on [Feb. 28th, 2006](https://ffxiclopedia.fandom.com/wiki/Adventuring_Fellow?oldid=52324)).

Since this was in the wiki even before ToAU was released, I'd think this is the way it was working at the time period in which Eden is set, which I believe is at some point in 2007?
