### ISSUE TITLE
Devil Manta unfishable after crash

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#2510]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver = 30181205_0

After the map cluster crash on March 7th, 2020 @ ~11:25:06PM EST, Devil Manta appears to be unfishable. Another fisher fished for 20 minutes with no Devil Manta. I then fished for 1 hour pulling up every monster caught, no manta. I went AFK and another fisher fished for 2 hours with no manta either.

**Comment by roriffxi** [comment]
There have been a few instances recently where Devil Manta just stops being fishable.  Have you noticed whether or not someone may have canceled or failed to reel it in while it was on the line?

**Comment by Mozzy4Ever** [comment]
Nope. After today's maintenance I was first in the zone and to make sure that didn't happen I fully fished up every ferocious bite. Fished for about 30 minutes and caught everything else but not manta. From the conversation I had with @Setz0r it doesn't seem to be an error caused by a player failing to fish it up

**Comment by Setz0r** [comment]
it's an issue with max random for choosing from mob catch list.  fix was pushed this morning but other issues caused us to revert.

**Comment by KnowOne134** [comment]
fixed i believe?

**Comment by Mozzy4Ever** [comment]
Havent seen anything in patch notes related to this being fixed

**Comment by Kharnek** [comment]
I tried fishing for it yesterday for close to 2 hours on 2 characters with no competition and was unable to fish him up even once.

**Comment by perkuprightmeow** [comment]
More tickets coming in about this, people are still unable to fish this up in an empty zone. 

In one case the zone R0'd while he was fighting a manta, not sure if relevant.

**Comment by aragan12** [comment]
This issue is still occuring as I cannot fish up the manta at all

**Comment by Setz0r** [comment]
fixed for upcoming patch
