### ISSUE TITLE
Blue Mage AF: wait times in between incorrect

### ISSUE THREAD

**Issue by KnowOne134** [EdenServer/community#4864]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
currently in game the wait times seem to be all 1 game day waits instead on midnight JP times as well as the purchased items
https://ffxiclopedia.fandom.com/wiki/Transformations?oldid=550908
https://ffxiclopedia.fandom.com/wiki/Omens?oldid=613443

**Comment by faivruit** [comment]
Same for COR AF pieces from Against All Odds / Leleroons Side Quests - Eden: 1 Game Day, Era: JP Midnight

https://ffxiclopedia.fandom.com/wiki/Against_All_Odds_-_Leleroon%27s_Sidequests?oldid=1404853
https://ffxiclopedia.fandom.com/wiki/Navigating_the_Unfriendly_Seas?oldid=649699

**Comment by KnowOne134** [comment]
Was resolved in 5/3/2023 update

**Comment by Deirdre5017** [comment]
This appears to be an issue again. 

Accidentally clicked the door in Bastok and received Corsair's Bottes before midnight JST when I turned them in the night before:

![image](https://github.com/EdenServer/community/assets/73006091/c2221f0e-cd62-4d32-b577-a4beded2783a)

I was then able to accept Corsair's Frac quest and turned in the items needed:

![image](https://github.com/EdenServer/community/assets/73006091/512a3b4d-cc90-4dc4-83a1-1b0886a66eec)

And the NPC gave the completed Frac to me less than 10 minutes later at the next game day (although it was next game day AND midnight JST so not sure if that factored into it):

![image](https://github.com/EdenServer/community/assets/73006091/930167ce-3be5-4c27-8714-92c001626191)

**Comment by E5una** [comment]
Confused on this one. 2008 bgwiki and ffxiclopedia both say you can pick up ur ordered BOU AF the next game day and that the JP midnight wait is the time before you can place an order for the NEXT piece.

I just waited until next game day and zoned but NPC still won’t give the item so I’m assuming it’s incorrectly set to JP midnight wait. Should I open a new bug report?
